version: "3.0"

services:
    
    mifilebeat:
        image: docker.elastic.co/beats/filebeat:7.10.1
        container_name: mifilebeat
        volumes:
            - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./datos.log:/tmp/datos.log

    milogstash:
        image: docker.elastic.co/logstash/logstash:7.10.1
        container_name: milogstash
        volumes:
            - ./logstash/apache-pipeline.conf:/usr/share/logstash/pipeline/apache-pipeline.conf
            - /home/ubuntu/environment/data/certificados/ca/ca.crt:/usr/share/logstash/certs/ca/ca.crt