version: "3.0"

services:
    nodo1:
        container_name: nodo1
        image: elasticsearch:7.10.1
        ports: 
            - 8080:9200
        environment:
            - node.name=nodo1
            - cluster.name=MiniCluster
            - cluster.initial_master_nodes=nodo1,nodo2,nodo3
            - discovery.seed_hosts=nodo2,nodo3
        volumes:
            - /home/ubuntu/environment/data/nodo1:/usr/share/elasticsearch/data
    nodo2:
        container_name: nodo2
        image: elasticsearch:7.10.1
        environment:
            - node.name=nodo2
            - cluster.name=MiniCluster
            - cluster.initial_master_nodes=nodo1,nodo2,nodo3
            - discovery.seed_hosts=nodo1,nodo3
        volumes:
            - /home/ubuntu/environment/data/nodo2:/usr/share/elasticsearch/data
            
    nodo3:
        container_name: nodo3
        image: elasticsearch:7.10.1
        environment:
            - node.name=nodo3
            - cluster.name=MiniCluster
            - cluster.initial_master_nodes=nodo1,nodo2,nodo3
            - discovery.seed_hosts=nodo1,nodo2
        volumes:
            - /home/ubuntu/environment/data/nodo3:/usr/share/elasticsearch/data
                        
    kibana:
        container_name: kibana
        image: kibana:7.10.1
        ports: 
            - 8081:5601
        environment:
            ELASTICSEARCH_HOSTS: http://nodo1:9200
            SERVER_NAME: kibana
            SERVER_HOST: kibana       
            
    cerebro:
        container_name: cerebro
        image: lmenezes/cerebro:0.9.3
        ports: 
            - 8082:9000